# Generated by Django 2.2.6 on 2019-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenci', '0002_auto_20191003_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miasto',
            options={'verbose_name_plural': 'miasta'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'studenci'},
        ),
        migrations.AlterModelOptions(
            name='uczelnia',
            options={'verbose_name_plural': 'uczelnie'},
        ),
        migrations.AlterField(
            model_name='student',
            name='dochod',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
