# Generated by Django 2.2.6 on 2019-10-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20191017_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skladnik',
            name='jarski',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeżeli składnik jest odpowiedni dla wegetarian', verbose_name='jarski?'),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='składnik'),
        ),
        migrations.AlterField(
            model_name='skladnik',
            name='pizze',
            field=models.ManyToManyField(blank=True, related_name='skladniki', to='pizza.Pizza'),
        ),
    ]
